/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CloudflareEnv` (hash: feb0f1e03bcd6670e25f0534af384810)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	NUXT_PUBLIC_API_BASE_URL: "/api/v1";
	WORKER_API_BASE_URL: "https://api.4ye.run/api/v1";
	API_SERVICE: Fetcher /* 4ye-run-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NUXT_PUBLIC_API_BASE_URL" | "WORKER_API_BASE_URL">> {}
}
