/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false --env-interface=ApiEnv worker/worker-configuration.d.ts` (hash: 0f9f9c3333716a10dea751b1a32e5814)
interface __BaseEnv_ApiEnv {
	ASSETS: R2Bucket;
	DB: D1Database;
	PUBLIC_RATE_LIMITER: RateLimit;
	ASSET_PUBLIC_BASE_URL: "https://img.4ye.run";
	ALLOWED_WEB_ORIGIN: "https://4ye.run";
	MAX_ASSET_SIZE_BYTES: "15728640";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ApiEnv {}
}
interface ApiEnv extends __BaseEnv_ApiEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASSET_PUBLIC_BASE_URL" | "ALLOWED_WEB_ORIGIN" | "MAX_ASSET_SIZE_BYTES">> {}
}
